### ISSUE TITLE
Archive files being corrupted by opine proxy

### ISSUE THREAD

**Issue by neonfuz** [asos-craigmorten/opine-http-proxy#10]
# Issue

Setup:

- Deno Version: 1.16.2
- v8 Version: v8 9.7.106.2
- Typescript Version: typescript 4.4.2
- Opine HTTP Proxy Version: 2.9.1
- Opine Version: 1.9.1

## Details

Archive files are being corrupted by opine proxy. To reproduce, run the app below and try fetching /archive.zip. In my testing, the resulting file is the same size as the original, but archive utilities throw errors saying it's corrupted.

```ts
import { opine } from "https://deno.land/x/opine@1.9.1/mod.ts";
import { proxy } from "https://deno.land/x/opineHttpProxy@2.9.1/mod.ts";

const app = opine();

app.get('/archive.zip', proxy('https://github.com', {
    proxyReqUrlDecorator(url, req) {
        url.pathname = '/asos-craigmorten/opine/archive/refs/tags/1.9.1.zip';
        return url;
    }
}));

app.listen(3000, () => console.log('listening on 3000'));
```

**Comment by cmorten** [comment]
Hey @neonfuz 👋 

Thanks for raising - can confirm the above snippet reproduces and see the following error when attempt to unzip:

![Screenshot 2021-11-21 at 16 14 11](https://user-images.githubusercontent.com/11313985/142769918-507bb6c8-7bdd-4bbc-a576-215d42936db6.png)

**Comment by cmorten** [comment]
Ok, got a hunch the issue is here --> https://github.com/asos-craigmorten/opine-http-proxy/blob/2.9.2/src/steps/sendProxyReq.ts#L58 where the response is being decoded to a utf-8 string and then transformed later back into an `ArrayBuffer` which suspect may be the cause, and regardless is superfluous in binary cases

**Comment by neonfuz** [comment]
I assumed it was some sort of decoding or parsing, tried fiddling with the options that existed but it didn't seem to fix the issue

**Comment by neonfuz** [comment]
Awesome, thanks for the quick fix!

**Comment by cmorten** [comment]
Hey @neonfuz, can you try out https://deno.land/x/opineHttpProxy@3.0.0 where believe have fixed the issue.

If find otherwise then please reopen the issue!

**Comment by neonfuz** [comment]
Sorry for not responding earlier, tested and the issue has been fixed for my usage, thanks!
