### ISSUE TITLE
resolveOptions method may only be the string "string" rather an any string

### ISSUE THREAD

**Issue by retog** [asos-craigmorten/opine-http-proxy#12]
https://github.com/cmorten/opine-http-proxy/blob/03f79cb2cf535529be7a3638048ef5481add104b/src/resolveOptions.ts#L170

Mandates the optional key to have the value `"string"`, it should either be `string` or `"GET"|"POST"|...`.

**Comment by cmorten** [comment]
Hey @retog :wave:

Thanks for raising this, I have released a fix in `3.0.1` (https://deno.land/x/opineHttpProxy@3.0.1).
