### ISSUE TITLE
Is possible to set socket with opine-reverse-proxy?

### ISSUE THREAD

**Issue by Relaxe111** [asos-craigmorten/opine-http-proxy#5]
Hello, i need to setup a reverse proxy which will allow for web sockets as well it is possible to do with opine-reverse-proxy?
thanks.

**Comment by cmorten** [comment]
Hi @Relaxe111 👋 This module does not support websocket proxying. I’m open to contributions if it’s something you’d want to give a go!

**Comment by Relaxe111** [comment]
Hello @cmorten thank you for quick reply. I would love to help but don't have idea where to start and how to do it. I can dedicate time to it and try to add this feat it, but I need some examples or help how-to do it.

**Comment by asos-craigmorten** [comment]
Hmm, unfortunately it's not something I've implemented before so beyond starting to google things I can't be of much help here 😅 

This library is based on https://github.com/villadora/express-http-proxy with adaptions for Deno / Opine - looking through it's issues it looks like it never supported websockets https://github.com/villadora/express-http-proxy/issues/448

From my experience with Node, the goto for ws proxying that I know of is to use the https://github.com/chimurai/http-proxy-middleware lib or https://github.com/http-party/node-http-proxy ( which provides the underlying proxy logic for the prior module, which is just an adaption for connect / Express like middleware ).

From the readme you can see that the http-proxy-middleware supports websocket proxying ( REF: https://github.com/chimurai/http-proxy-middleware#websocket ). So I'd recommend diving into those two repo's code to see how they are doing it.

You _could_ also try using one of those libraries directly in Deno by making use of a CDN that polyfills ( e.g. esm.sh or Skypack ) or using Deno's Node compatibility layer, but I suspect that you may struggle with that as Deno doesn't have http polyfills in it's std library yet ( REF: https://deno.land/std@0.92.0/node#supported-builtins ).

I imagine this might be something a few folks might need, so could be a good opportunity to create a new third party module which can be contributed to the Deno userland!

Be sure to reach out on the [Deno discord](https://discord.com/channels/684898665143206084/689420767620104201), there are some awesome folks in the community who may be able to help more, or might have already created a solution!

**Comment by cmorten** [comment]
Not looking to implement this as falls outside of the scope of this library. If folks want to implement and contribute then feel free to re-open this issue / raise a new one!
